### ISSUE TITLE
Support for UE5

### ISSUE THREAD

**Issue by DervexDev** [razerofficial/UE4_XDK_SampleApp#6]
I think it would be nice to have this plugin on Unreal Engine 5.
Current version of Chroma SDK won't compile on latest version of engine obviously.

**Comment by tgraupmann** [comment]
I'll look into that. When I tried the UE5 pre-releases the demos were enormous and the editor was laggy. I'll look into making the new version compatible.

**Comment by tgraupmann** [comment]
To get the VS 2022 solution to generate make the following changes:
---

* UE4ChromaSDKRT\UE4ChromaSDKRT.uproject - Modules no longer supports "Type": "Developer"

```
{
	"FileVersion": 3,
	"EngineAssociation": "5.0",
	"Category": "",
	"Description": "",
	"Modules": [
		{
			"Name": "UE4ChromaSDKRT",
			"Type": "Runtime"
		}
	]
}
```

*  UE4ChromaSDKRT\Plugins\ChromaSDKPlugin\Source\ChromaSDKPlugin\ChromaSDKPlugin.Build.cs - Definitions changed to PrivateDefinitions and PublicDefinitions
```
PrivateDefinitions.Add("CHECK_CHROMA_LIBRARY_SIGNATURE=1");
PublicDefinitions.Add("CHECK_CHROMA_LIBRARY_SIGNATURE=1");
```
---

* Fix error - 'byte': ambiguous symbol - https://developercommunity.visualstudio.com/t/error-c2872-byte-ambiguous-symbol/93889

For this one, I need to enable showIncludes - https://docs.unrealengine.com/5.0/en-US/build-configuration-for-unreal-engine/

* Edit: %appdata%\Unreal Engine\UnrealBuildTool\BuildConfiguration.xml

```
<?xml version="1.0" encoding="utf-8" ?>
<Configuration xmlns="https://www.unrealengine.com/BuildConfiguration">
  <WindowsPlatform>
    <bShowIncludes>true</bShowIncludes>
  </WindowsPlatform>
</Configuration>
```

And then you can see in the output that `rpcndr.h` is included by including `AllowWindowsPlatformTypes.h`.

Although this looks more like a Windows SDK bug.

```
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared\rpcndr.h(192): error C2872: 'byte': ambiguous symbol
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared\rpcndr.h(191): note: could be 'unsigned char byte'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\INCLUDE\cstddef(29): note: or       'std::byte'
```

**Comment by Thomas-is-dev** [comment]
When UE5 support ?

**Comment by MinoDab492** [comment]
@tgraupmann You should submit that as a pull request, it would be great to have functional UE5 support without having to do so much work.

**Comment by tgraupmann** [comment]
I need to port one piece at a time until it all works. I haven't needed to support a shipping title in UE5 yet so I haven't prioritized this over my other tasks yet.

**Comment by tgraupmann** [comment]
I added extended keyboard and Unicode path support for UE4. The next step is to attempt the UE5 upgrade again.
https://github.com/razerofficial/UE4_XDK_SampleApp/tree/SUPPORT_UNICODE

**Comment by tgraupmann** [comment]
I'll copy the repository to my username until the update works and then I'll post on `razerofficial`.
https://github.com/tgraupmann/UE5_XDK_SampleApp

**Comment by tgraupmann** [comment]
Okay I have it working.
https://github.com/razerofficial/UE5_XDK_SampleApp

The last struggle was std::byte collisions. I ended up just removing `using namespace std;` and just used std::wstring etc where I needed it. That was a fast fix and now the samples are up and running in UE5.

**Comment by DervexDev** [comment]
@tgraupmann added support for UE5 in this separate [repo](https://github.com/razerofficial/UE5_XDK_SampleApp). Thanks!
